# Generated by Django 4.1.3 on 2023-01-27 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("out_trade_num", models.UUIDField()),
                ("trade_no", models.CharField(max_length=120)),
                ("order_num", models.CharField(max_length=100)),
                ("status", models.CharField(default="待支付", max_length=20)),
                ("payway", models.CharField(default="alipay", max_length=20)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userapp.address",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userapp.userinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goodsid", models.PositiveBigIntegerField()),
                ("colorid", models.PositiveBigIntegerField()),
                ("sizeid", models.PositiveBigIntegerField()),
                ("count", models.PositiveBigIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orderapp.order"
                    ),
                ),
            ],
        ),
    ]
