# Generated by Django 4.1.3 on 2022-12-07 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                ("areaid", models.IntegerField(primary_key=True, serialize=False)),
                ("areaname", models.CharField(max_length=50)),
                ("parentid", models.IntegerField()),
                ("arealevel", models.IntegerField()),
                ("status", models.IntegerField()),
            ],
            options={
                "db_table": "area",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GoodsappCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("cname", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "goodsapp_category",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GoodsappColor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("colorname", models.CharField(max_length=10)),
                ("colorurl", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "goodsapp_color",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GoodsappGoods",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("gname", models.CharField(max_length=100)),
                ("gdesc", models.CharField(max_length=200)),
                ("oldprice", models.DecimalField(decimal_places=2, max_digits=5)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "db_table": "goodsapp_goods",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GoodsappGoodsdetail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("gdurl", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "goodsapp_goodsdetail",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GoodsappGoodsdetailname",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("gdname", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "goodsapp_goodsdetailname",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GoodsappInventory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("count", models.PositiveBigIntegerField()),
            ],
            options={
                "db_table": "goodsapp_inventory",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GoodsappSize",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sname", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "goodsapp_size",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uname", models.CharField(max_length=100, verbose_name="用户名")),
                ("pwd", models.CharField(max_length=100, verbose_name="密码")),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aname", models.CharField(max_length=30)),
                ("aphone", models.CharField(max_length=11)),
                ("addr", models.CharField(max_length=100)),
                ("isdefault", models.BooleanField(default=False)),
                (
                    "userinfo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userapp.userinfo",
                    ),
                ),
            ],
        ),
    ]
